version: "3.4"
services:
  swoole:
    image: "twosee/swoole-coroutine"
    ports:
      - "9501:9501"
    volumes:
      - D:\code\swoole:/app/src:rw
    restart: always
    depends_on:
      - mysql
    command: php /app/src/server.php start

  mysql:
    image: "twosee/swoole-coroutine:mysql"
    ports:
      - "9502:3306"
    volumes:
      - D:\data\mysql\data:/var/lib/mysql:rw
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_here
      MYSQL_DATABASE: test
      MYSQL_USER: php
      MYSQL_PASSWORD: php_user_password_here

  redis:
    image: "twosee/swoole-coroutine:redis"
    ports:
      - "9503:6379"
    volumes:
      - D:\data\redis\data:/var/lib/redis:rw
    sysctls:
        net.core.somaxconn: 65535
    restart: always

  inotify:
    image: "twosee/swoole-coroutine:inotify"
    volumes:
      - D:\data:/app:rw
    restart: always
    environment:
      APP_ENV: dev # or product
    working_dir: /app/util
    command: /bin/bash inotify.sh